---
- name: create dir
  hosts: all
  become: true
  tasks:
        - name: create dir
          file:
                  path: /home/itadmin/usingGIT/{{item}} 
                  state: touch
          with-items:
           - Using loop1
           - Using loop2
           - Using loop3
